Feature/create app project (#9)
* Initial commit of Project pages & components

* DenseLayout appends current url to /context link on logo

* Settings pages ui updates

* Consistent headers for Brand, Project, Settings

These header styles (.header, etc) really should be DRY

* Initial dev for ProjectIndex; Addition of BrandSelectorComponent

* Better UI consistency between Brand & Project Index

* ProjectFilters markup & styling

Todo: functionality

* BrandSelectorComponent to allow null as default

* ProjectFilters added brand-selector component

* Addition of state: SearchProject

* Addition of helper: plainToFlattenObject

* Relocate projects loading bar to ProjectIndex

* ProjectFilters functionality with QueryParams & NGXS Form state

* Fix SignInComponent button as type submit

* Addition of “filters” and “results” states to SearchProject

* Addition of rendering Tags for project filters

* Upgrade NGXS to 3.7.0; Fix bug for Account.Refresh()

Error: “This action doesn't have a type property: Object at InternalDispatcher.dispatchSingle”

* Addition of UiPreferences child state of Ui state

UiPreferences state will be persisted as it deals with UI Preferences.

* ProjectIndex uses UiPreferencesState.projectIndexDrawerOpened

persist whether the filters panel is opened or closed.

* BrandState selectors “id” and “ids”

* Addition of components: BrandDetail and BrandList

* ProjectIndex filter tags render brand.id using brand-detail

* BrandSelector [active] binds to a string id

* ProjectFilters and BrandSelector are functional!

* ProjectFilters actions bar is position sticky to bottom of component for better UX

* Prettied up BrandFilters

* ProjectIndex resolved issue for removing brand; added ChangeDetection.OnPush

* Ability to remove filters via tags; Relocated SearchProject.SetFilters to ProfjectIndex

* Close ProjectFilters drawer on small screen after form submit

* Renamed SearchProject to ProjectSearch

* Render ProjectSearch.results with Greeking

* Defaulting drawerMode to “push” instead of “side”

Need to see which Jay thinks the user would prefer.

* Update navigation manifest to include children for Brands & Projects

* UI consistency for %entity-detail and Brand & Project New pages

* ProjectForm has initial fields wired up for Project.New

* ProjectForm functionality for slug validation and date fields

* Ability to CREATE Projects!

* Added ProjectDetailGuard & 404 page use query params

* ProjectEdit populates ProjectForm

allow current slug to bypass validation for ProjectEdit

* ProjectEdit complete!